apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: publisher
  name: publisher-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher
        component: publisher
    spec:
      containers:
      - image: quintindk/py-publisher
        name: py-publisher
        resources:
          limits:
            cpu: 100m