apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
    targetPort: 35672
    name: rabbitmq
  - port: 36672
    targetPort: 15672
    name: management
  - port: 37672
    targetPort: 25672
    name: gossip
  selector:
    app: rabbitmq-pubsub
    component: rabbitmq
  type: NodePort