apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  - port: 25672
    name: gossip
  selector:
    app: rabbitmq-pubsub
    component: rabbitmq