apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  - port: 15672
  - port: 25672
  selector:
    app: rabbitmq-pubsub
    component: rabbitmq