apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: subscriber
  name: subscriber-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriber
        component: subscriber
    spec:
      containers:
      - image: quintindk/py-subscriber
        name: py-subscriber
        resources:
          limits:
            cpu: 100m